site_name: SIC Wiki
  
site_author: Suntion
copyright: MIT
site_dir: site/SptItemCreatorWiki



theme:
  name: material
  custom_dir: custom_theme/
  user_color_mode_toggle: true
  language: zh # material 页面语言

extra: 
  alternate:
    - name: 中文
      link: /zh/
      lang: zh
    - name: English
      link: /en/
      lang: en
  sitemap:
    filename: sitemap.xml

use_directory_urls: false
